USE NOTA_FISCAL_NORMALIZADA;

-- FORMA CLÁSSICA DE CONSUTAS COMBINADAS 
SELECT NOTA_FISCAL.*, ITEM_NOTA_FISCAL. 
FROM NOTA_FISCAL, ITEM_NOTA_FISCAL
WHERE NOTA_FISCAL.NRO_NOTA = ITEM_NOTA_FISCAL.NRO_NOTA;

-- PODEMOS DEFINIR ALIAS (APELIDOS) PARA TABELAS E FACILITAR A CODIFICAÇÃoptimize
SELECT NF.NRO_NOTA, INF.DT_EMISSAO, NF.VALOR_TOTAL,
INF.COD_PRODUTO, P.DESC_PRODUTO, P.UN_MED,
INF.QTD_PRODUTO, INF.VL_PRECO, INF.VL_TOTAL

FROM 
   NOTA_FISCAL AS NF,
   ITEM_NOTA_FISCAL AS INF,
   PRODUTO AS P
WHERE 
   NF.NRO_NOTA = INF.NRO_NOTA
   AND INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY
  NF.NRO_NOTA;