
-- CRIAÇÃO DO BANCO DE DADOS E TABELA DA VETERINÁRIA

CREATE DATABASE VETERINARIA;

USE VETERINARIA;

CREATE TABLE TIPOS_ANIMAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ESPECIE VARCHAR(50)
);

CREATE TABLE ANIMAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ESPECIE VARCHAR(50),
	NOME VARCHAR(100),
    DT_NASC DATE NOT NULL,
    COR VARCHAR(15),
    PESO INT NOT NULL,
    ALTURA INT NOT NULL,
    ID_TIPOS_ANIMAIS INT NOT NULL,
    CONSTRAINT FK_ID_TIPOS_ANIMAIS
		FOREIGN KEY (ID_TIPOS_ANIMAIS)
        REFERENCES TIPOS_ANIMAIS(ID)
);

CREATE TABLE VACINACAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_ANIMAL INT NOT NULL,
	NOME_VACINA VARCHAR(100),
	DT_APLIC DATE,
    CONSTRAINT FK_ID_ANIMAL
		FOREIGN KEY (ID_ANIMAL)
        REFERENCES ANIMAIS(ID)
);

SELECT * FROM `TIPOS_ANIMAIS`;
SELECT ID, ESPECIE FROM TIPOS_ANIMAIS;

SELECT * FROM `ANIMAIS`;
SELECT ID, ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA FROM ANIMAIS;

SELECT * FROM `VACINACAO`;
SELECT ID, ID_ANIMAL, NOME_VACINA, DT_APLIC FROM VACINACAO;

INSERT INTO TIPOS_ANIMAIS (ESPECIE)
VALUES ('BOVINO');
INSERT INTO TIPOS_ANIMAIS (ESPECIE)
VALUES ('SUÍNO');
INSERT INTO TIPOS_ANIMAIS (ESPECIE)
VALUES ('CAPRINO');
INSERT INTO TIPOS_ANIMAIS (ESPECIE)
VALUES ('FELINO');
INSERT INTO TIPOS_ANIMAIS (ESPECIE)
VALUES ('CANINO');

INSERT INTO ANIMAIS (ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA, ID_TIPOS_ANIMAIS)
VALUES ('BOVINO', 'GEODUDE', '2003-05-03', 'MARROM', 100000 ,145, 1);
INSERT INTO ANIMAIS (ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA, ID_TIPOS_ANIMAIS)
VALUES ('SUÍNO', 'PEPPA', '1998-08-01', 'ROSA', 80000, 120, 2);
INSERT INTO ANIMAIS (ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA, ID_TIPOS_ANIMAIS)
VALUES ('CAPRINO', 'FURA-FUÇA', '2023-06-08', 'AMARELO', 70000, 130, 3);
INSERT INTO ANIMAIS (ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA, ID_TIPOS_ANIMAIS)
VALUES ('FELINO', 'MARTELO', '2020-04-05', 'PRETO', 8000, 90, 4);
INSERT INTO ANIMAIS (ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA, ID_TIPOS_ANIMAIS)
VALUES ('CANINO', 'ANAKIN', '2012-12-19', 'PARDO', 10000, 110, 5);

INSERT INTO VACINACAO (ID_ANIMAL, NOME_VACINA, DT_APLIC)
VALUES (2, 'ANTI-TÉTANO', '2005-02-07');
INSERT INTO VACINACAO (ID_ANIMAL, NOME_VACINA, DT_APLIC)
VALUES (1, 'ANTI-PULGA', '2009-07-11');
INSERT INTO VACINACAO (ID_ANIMAL, NOME_VACINA, DT_APLIC)
VALUES (3, 'POLIOMELITE', '2025-11-09');
INSERT INTO VACINACAO (ID_ANIMAL, NOME_VACINA, DT_APLIC)
VALUES (5, 'CHAGAS', '2013-01-23');
INSERT INTO VACINACAO (ID_ANIMAL, NOME_VACINA, DT_APLIC)
VALUES (4, 'COVID', '2021-12-25');

-- Com base no banco de dados de vetrinária, elabore consultas SQL para:
-- 1. Qual a quantidade de animais registrados no sistema?
-- 2. Qual o total de vacinações registradas no sistema?
-- 3. Quantos animais temos registrados para cada tipo de animal (canino, felino etc)
-- 4. Qual a categoria de animais que mais recebeu vacinas? 

SELECT COUNT(*) FROM VETERINARIA.ANIMAIS;
 
SELECT COUNT(*) FROM VETERINARIA.VACINACAO;

SELECT t.ESPECIE, COUNT(a.ID) AS QTD_ANIMAIS
FROM TIPOS_ANIMAIS t
INNER JOIN ANIMAIS a ON t.ID = a.ID_TIPOS_ANIMAIS
GROUP BY t.ESPECIE;

SELECT t.ESPECIE, COUNT(v.ID) AS QTD_VACINAS
FROM TIPOS_ANIMAIS t
INNER JOIN ANIMAIS a ON t.ID = a.ID_TIPOS_ANIMAIS
INNER JOIN VACINACAO v ON a.ID = v.ID_ANIMAL
GROUP BY t.ESPECIE
ORDER BY QTD_VACINAS DESC
LIMIT 1;
